// Autogenerated

import { defineConfig } from '@unocss/vite'
import { presetMini } from '@unocss/preset-mini'

export default defineConfig({
  presets: [presetMini()],
  shortcuts: {
    ceaf38: 'text-orange-300',
    c3e8e8: 'text-lg text-white font-thin',
    d3er1f: 'font-bold text-green',
    ve431d:
      'sm:w-[25vw] w-[50vw] my-4 mx-8 px-2 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm'
  }
})
